### ISSUE TITLE
user-data not being applied

### ISSUE THREAD

**Issue by Swampcritter** [lefeck/ubuntu-autoinstall-generator-tools#1]
I used the generator and created a custom user-data file for building out a LVM configured Ubuntu 22.04 instance and yet none of the settings are being applied. Is there something I am doing that is wrong or does something else need to be done to order for the custom layout? 

I built the new ISO via: sudo ./ubuntu-autoinstall-generator-tools.sh -n jammy -u user-data

User Data File -- [user-data.txt](https://github.com/lefeck/ubuntu-autoinstall-generator-tools/files/13759530/user-data.txt)

**Comment by lefeck** [comment]
You can also specify the -a option, and to build a new image it is recommended that you use the -d parameter to specify the name of the new image to build, as follows.

```shell
sudo ./ubuntu-autoinstall-generator-tools.sh  -n  jammy -a  -u user-data -d ubuntu22-autoinstall-jammy-test.iso
```


In addition, I found some small errors in your user-data definition parameter, corrected configuration file parameters are as follows: 
```yaml
#cloud-config
autoinstall:
  refresh-installer:
    # Whether to update or not. default: no
    update: yes
    # The channel to check for updates.
    channel: "stable/ubuntu-$REL"
  updates: all
  identity:
    hostname: ubuntu-server
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
    username: ubuntu
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      # configure network inteface
      eth0:
        addresses:
          - 10.20.5.10/24
        nameservers:
          addresses:
           - 10.20.1.5
           - 10.20.1.6
          search:
           - ddc.local
        routes:
          - to: default
            via: 10.20.5.1
    version: 2
  ssh:
    install-server: true
    allow-pw: true
  storage:
    config:
    - { ptable: gpt, path: /dev/sda, wipe: superblock-recursive, preserve: false, grub_device: true, type: disk, id: disk-sda }
    - { type: partition, wipe: superblock-recursive, preserve: false, number: 1, device: disk-sda, flag: bios_grub, size: 1M, id: bios-grub }
    - { type: partition, wipe: superblock, preserve: false, number: 2, device: disk-sda, flag: boot, size: 1G, id: sda-boot }
    - { type: partition, wipe: superblock, preserve: false, number: 3, device: disk-sda, size: -1 , id: sda-lvm }
    - { type: lvm_volgroup, name: vg00, devices: [sda-lvm], id: vg00 }
    - { type: lvm_partition, volgroup: vg00, id: lvroot, name: lvroot, size: 20G }
    - { type: lvm_partition, volgroup: vg00, id: lvswap, name: lvswap, size: 4G }
    - { type: lvm_partition, volgroup: vg00, id: lvhome, name: lvhome, size: 5G }
    - { type: lvm_partition, volgroup: vg00, id: lvtmp, name: lvtmp, size: 2G }
    - { type: lvm_partition, volgroup: vg00, id: lvopt, name: lvopt, size: 2G }
    - { type: lvm_partition, volgroup: vg00, id: lvvar, name: lvvar, size: 10G }
    - { type: format, fstype: ext4, volume: sda-boot, id: sda-boot-fs }
    - { type: format, fstype: ext4, volume: lvroot, id: lv-root-fs }
    - { type: format, fstype: swap, volume: lvswap, id: lv-swap-fs }
    - { type: format, fstype: ext4, volume: lvhome, id: lv-home-fs }
    - { type: format, fstype: ext4, volume: lvtmp, id: lv-tmp-fs }
    - { type: format, fstype: ext4, volume: lvopt, id: lv-opt-fs }
    - { type: format, fstype: ext4, volume: lvvar, id: lv-var-fs }
    - { type: mount, path: /boot, id: m-boot, device: sda-boot-fs }
    - { type: mount, path: /, id: m-root, device: lv-root-fs }
    - { type: mount, path: '', id: m-swap, device: lv-swap-fs }
    - { type: mount, path: /home, id: m-home, device: lv-home-fs }
    - { type: mount, path: /tmp, id: m-tmp, device: lv-tmp-fs }
    - { type: mount, path: /opt, id: m-opt, device: lv-opt-fs }
    - { type: mount, path: /var, id: m-var, device: lv-var-fs }
  version: 1
  packages:
    - bash-completion
    - cloud-utils
    - cloud-guest-utils
    - git
    - curl
    - mlocate
    - resolvconf
    - htop
    - net-tools
    - dnsutils
    - aptitude
    - unzip
```

Network section, missing network interface name, I'm not sure about your network interface name, I customized it to eth0, you need to change it to match the actual one.
