### ISSUE TITLE
Examples of user-data for using dm_crypt?

### ISSUE THREAD

**Issue by maworsham** [lefeck/ubuntu-autoinstall-generator-tools#6]
The user-data examples are great, but you wouldn't happen to have an example implementing dm_crypt at the LVM level?

I've tried something like this as a test, but it bugs out (see following curtin-install error) and I don't know who to turn to.

```
Preparing partition location on disk /dev/sda
Wiping 1M on /dev/sda at offset 1611661312
Running command ['sgdisk', '--new', '3:3147776:419428351', '--typecode=3:8300', '/dev/sda'] with allowed return codes [0] (capture=True)
Running command ['udevadm', 'info', '--query=property', '--export', '/dev/sda'] with allowed return codes [0] (capture=True)
/dev/sda is multipath device? False
Running command ['blockdev', '--rereadpt', '/dev/sda'] with allowed return codes [0] (capture=True)
Running command ['udevadm', 'settle'] with allowed return codes [0] (capture=False)
TIMED udevadm_settle(): 0.369
TIMED udevadm_settle(exists='/dev/sda3'): 0.000
finish: cmd-install/stage-partitioning/builtin/cmd-block-meta: SUCCESS: configuring partition: sda-lvm
start: cmd-install/stage-partitioning/builtin/cmd-block-meta: configuring dm_crypt: dm_crypt-0
get_path_to_storage_volume for volume sda-lvm({'device': 'disk-sda', 'size': 213135654912, 'wipe': 'superblock', 'number': 3, 'preserve': False, 'grub_device': False, 'id': 'sda-lvm', 'type': 'partition'})
get_path_to_storage_volume for volume disk-sda({'ptable': 'gpt', 'path': '/dev/sda', 'wipe': 'superblock', 'preserve': False, 'name': '', 'grub_device': False, 'id': 'disk-sda', 'type': 'disk'})
Running command ['udevadm', 'info', '--query=property', '--export', '/dev/sda'] with allowed return codes [0] (capture=True)
/dev/sda is multipath device member? False
Running command ['partprobe', '/dev/sda'] with allowed return codes [0, 1] (capture=False)
Running command ['udevadm', 'settle'] with allowed return codes [0] (capture=False)
TIMED udevadm_settle(): 0.196
devsync happy - path /dev/sda now exists
return volume path /dev/sda
Running command ['partprobe', '/dev/sda'] with allowed return codes [0, 1] (capture=False)
Running command ['udevadm', 'settle'] with allowed return codes [0] (capture=False)
TIMED udevadm_settle(): 0.251
devsync happy - path /dev/sda now exists
return volume path /dev/sda3
Checking if zkey encryption is supported...
Loading kernel module pkey via modprobe
Running command ['modprobe', '--use-blacklist', 'pkey'] with allowed return codes [0] (capture=False)
modprobe: FATAL: Module pkey not found in directory /lib/modules/5.15.0-119-generic
Failed to load 'pkey' kernel module
Using cryptsetup on /dev/sda3
Running command ['cryptsetup', 'luksFormat', '/dev/sda3', '/boot/keyfile'] with allowed return codes [0] (capture=False)
Failed to open key file.
An error occured handling 'dm_crypt-0': ProcessExecutionError - Unexpected error while running command.
Command: ['cryptsetup', 'luksFormat', '/dev/sda3', '/boot/keyfile']
Exit code: 1
Reason: -
Stdout: ''
Stderr: ''
finish: cmd-install/stage-partitioning/builtin/cmd-block-meta: FAIL: configuring dm_crypt: dm_crypt-0
TIMED BLOCK_META: 11.402
finish: cmd-install/stage-partitioning/builtin/cmd-block-meta: FAIL: curtin command block-meta
Traceback (most recent call last):
  File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/commands/main.py", line 202, in main
    ret = args.func(args)
  File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/log.py", line 97, in wrapper
    return log_time("TIMED %s: " % msg, func, *args, **kwargs)
  File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/log.py", line 79, in log_time
    return func(*args, **kwargs)
  File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/commands/block_meta.py", line 127, in block_meta
    return meta_custom(args)
  File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/commands/block_meta.py", line 2278, in meta_custom
    handler(command, storage_config_dict, context)
  File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/commands/block_meta.py", line 1706, in dm_crypt_handler
    util.subp(cmd)
  File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/util.py", line 323, in subp
    return _subp(*args, **kwargs)
  File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/util.py", line 172, in _subp
    raise ProcessExecutionError(stdout=out, stderr=err,
curtin.util.ProcessExecutionError: Unexpected error while running command.
Command: ['cryptsetup', 'luksFormat', '/dev/sda3', '/boot/keyfile']
Exit code: 1
Reason: -
Stdout: ''
Stderr: ''
Unexpected error while running command.
Command: ['cryptsetup', 'luksFormat', '/dev/sda3', '/boot/keyfile']
Exit code: 1
Reason: -
Stdout: ''
Stderr: ''
curtin: Installation failed with exception: Unexpected error while running command.
Command: ['curtin', 'block-meta', 'simple']
Exit code: 3
```

My current storage config that I need help correcting...
```
  storage:
    grub:
      reorder_uefi: False
    swap:
      size: 0
    config:
      - { id: disk-sda, ptable: gpt, path: /dev/sda, type: disk, wipe: superblock }
      - { device: disk-sda, grub_device: true, flag: boot, id: sda-efi, number: 1, size: 512MB, type: partition, wipe: superblock }
      - { device: disk-sda, id: sda-boot, number: 2, size: 1GB, type: partition, wipe: superblock }
      - { device: disk-sda, id: sda-lvm, number: 3, size: -1, type: partition, wipe: superblock }
      - { type: dm_crypt, volume: sda-lvm, keyfile: /boot/keyfile, recovery_keyfile: /tmp/luks-recovery-key-3xmf7tb5, recovery_live_location: /root/recovery-key.txt, recovery_backup_location: var/log/installer/recovery-key.txt, path: /dev/mapper/dm_crypt-0, id: dm_crypt-0 }
      - { type: lvm_volgroup, name: vg00, devices: [dm_crypt-0], id: vg00 }
      - { type: lvm_partition, volgroup: vg00, id: lvroot, name: lvroot, size: 50G }
      - { type: lvm_partition, volgroup: vg00, id: lvswap, name: lvswap, size: 10G }
      - { type: lvm_partition, volgroup: vg00, id: lvhome, name: lvhome, size: 5G }
      - { type: lvm_partition, volgroup: vg00, id: lvtmp, name: lvtmp, size: 1G }
      - { type: lvm_partition, volgroup: vg00, id: lvvar, name: lvvar, size: 20G }
      - { type: format, fstype: fat32, volume: sda-efi, id: sda-efi-fs }
      - { type: format, fstype: ext4, volume: sda-boot, id: sda-boot-fs }
      - { type: format, fstype: ext4, volume: lvroot, id: lv-root-fs }
      - { type: format, fstype: swap, volume: lvswap, id: lv-swap-fs }
      - { type: format, fstype: ext4, volume: lvhome, id: lv-home-fs }
      - { type: format, fstype: ext4, volume: lvtmp, id: lv-tmp-fs }
      - { type: format, fstype: ext4, volume: lvvar, id: lv-var-fs }
      - { type: mount, path: /boot/efi, id: m-efi, device: sda-efi-fs }
      - { type: mount, path: /boot, id: m-boot, device: sda-boot-fs }
      - { type: mount, path: /, id: m-root, device: lv-root-fs }
      - { type: mount, path: '', id: m-swap, device: lv-swap-fs }
      - { type: mount, path: /home, id: m-home, device: lv-home-fs }
      - { type: mount, path: /tmp, id: m-tmp, device: lv-tmp-fs }
      - { type: mount, path: /var, id: m-var, device: lv-var-fs }
  version: 1
  packages:
    - bash-completion
    - cloud-utils
    - cloud-guest-utils
    - git
    - curl
    - mlocate
    - resolvconf
    - htop
    - net-tools
    - dnsutils
    - aptitude
    - unzip
    - cryptsetup
    - lvm2
  early-commands:
    - curtin in-target --target=/target -- modprobe pkey
    - curtin in-target --target=/target -- dd if=/dev/urandom of=/boot/keyfile bs=1024 count=4
    - curtin in-target --target=/target -- chmod 0400 /boot/keyfile
    - curtin in-target --target=/target -- dd if=/dev/urandom of=/tmp/luks-recovery-key-3xmf7tb5 bs=1024 count=4
    - curtin in-target --target=/target -- chmod 0400 /tmp/luks-recovery-key-3xmf7tb5
    - curtin in-target --target=/target -- cp /tmp/luks-recovery-key-3xmf7tb5 /root/recovery-key.txt
    - curtin in-target --target=/target -- cp /tmp/luks-recovery-key-3xmf7tb5 /var/log/installer/recovery-key.txt
  late-commands:
    - curtin in-target --target=/target -- cryptsetup luksAddKey /dev/sda3 /boot/keyfile
    - echo '%ubuntu ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/ubuntu
```

**Comment by lefeck** [comment]
> The user-data examples are great, but you wouldn't happen to have an example implementing dm_crypt at the LVM level?
> 
> I've tried something like this as a test, but it bugs out (see following curtin-install error) and I don't know who to turn to.
> 
> ```
> Preparing partition location on disk /dev/sda
> Wiping 1M on /dev/sda at offset 1611661312
> Running command ['sgdisk', '--new', '3:3147776:419428351', '--typecode=3:8300', '/dev/sda'] with allowed return codes [0] (capture=True)
> Running command ['udevadm', 'info', '--query=property', '--export', '/dev/sda'] with allowed return codes [0] (capture=True)
> /dev/sda is multipath device? False
> Running command ['blockdev', '--rereadpt', '/dev/sda'] with allowed return codes [0] (capture=True)
> Running command ['udevadm', 'settle'] with allowed return codes [0] (capture=False)
> TIMED udevadm_settle(): 0.369
> TIMED udevadm_settle(exists='/dev/sda3'): 0.000
> finish: cmd-install/stage-partitioning/builtin/cmd-block-meta: SUCCESS: configuring partition: sda-lvm
> start: cmd-install/stage-partitioning/builtin/cmd-block-meta: configuring dm_crypt: dm_crypt-0
> get_path_to_storage_volume for volume sda-lvm({'device': 'disk-sda', 'size': 213135654912, 'wipe': 'superblock', 'number': 3, 'preserve': False, 'grub_device': False, 'id': 'sda-lvm', 'type': 'partition'})
> get_path_to_storage_volume for volume disk-sda({'ptable': 'gpt', 'path': '/dev/sda', 'wipe': 'superblock', 'preserve': False, 'name': '', 'grub_device': False, 'id': 'disk-sda', 'type': 'disk'})
> Running command ['udevadm', 'info', '--query=property', '--export', '/dev/sda'] with allowed return codes [0] (capture=True)
> /dev/sda is multipath device member? False
> Running command ['partprobe', '/dev/sda'] with allowed return codes [0, 1] (capture=False)
> Running command ['udevadm', 'settle'] with allowed return codes [0] (capture=False)
> TIMED udevadm_settle(): 0.196
> devsync happy - path /dev/sda now exists
> return volume path /dev/sda
> Running command ['partprobe', '/dev/sda'] with allowed return codes [0, 1] (capture=False)
> Running command ['udevadm', 'settle'] with allowed return codes [0] (capture=False)
> TIMED udevadm_settle(): 0.251
> devsync happy - path /dev/sda now exists
> return volume path /dev/sda3
> Checking if zkey encryption is supported...
> Loading kernel module pkey via modprobe
> Running command ['modprobe', '--use-blacklist', 'pkey'] with allowed return codes [0] (capture=False)
> modprobe: FATAL: Module pkey not found in directory /lib/modules/5.15.0-119-generic
> Failed to load 'pkey' kernel module
> Using cryptsetup on /dev/sda3
> Running command ['cryptsetup', 'luksFormat', '/dev/sda3', '/boot/keyfile'] with allowed return codes [0] (capture=False)
> Failed to open key file.
> An error occured handling 'dm_crypt-0': ProcessExecutionError - Unexpected error while running command.
> Command: ['cryptsetup', 'luksFormat', '/dev/sda3', '/boot/keyfile']
> Exit code: 1
> Reason: -
> Stdout: ''
> Stderr: ''
> finish: cmd-install/stage-partitioning/builtin/cmd-block-meta: FAIL: configuring dm_crypt: dm_crypt-0
> TIMED BLOCK_META: 11.402
> finish: cmd-install/stage-partitioning/builtin/cmd-block-meta: FAIL: curtin command block-meta
> Traceback (most recent call last):
>   File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/commands/main.py", line 202, in main
>     ret = args.func(args)
>   File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/log.py", line 97, in wrapper
>     return log_time("TIMED %s: " % msg, func, *args, **kwargs)
>   File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/log.py", line 79, in log_time
>     return func(*args, **kwargs)
>   File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/commands/block_meta.py", line 127, in block_meta
>     return meta_custom(args)
>   File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/commands/block_meta.py", line 2278, in meta_custom
>     handler(command, storage_config_dict, context)
>   File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/commands/block_meta.py", line 1706, in dm_crypt_handler
>     util.subp(cmd)
>   File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/util.py", line 323, in subp
>     return _subp(*args, **kwargs)
>   File "/snap/subiquity/6066/lib/python3.10/site-packages/curtin/util.py", line 172, in _subp
>     raise ProcessExecutionError(stdout=out, stderr=err,
> curtin.util.ProcessExecutionError: Unexpected error while running command.
> Command: ['cryptsetup', 'luksFormat', '/dev/sda3', '/boot/keyfile']
> Exit code: 1
> Reason: -
> Stdout: ''
> Stderr: ''
> Unexpected error while running command.
> Command: ['cryptsetup', 'luksFormat', '/dev/sda3', '/boot/keyfile']
> Exit code: 1
> Reason: -
> Stdout: ''
> Stderr: ''
> curtin: Installation failed with exception: Unexpected error while running command.
> Command: ['curtin', 'block-meta', 'simple']
> Exit code: 3
> ```
> 
> My current storage config that I need help correcting...
> 
> ```
>   storage:
>     grub:
>       reorder_uefi: False
>     swap:
>       size: 0
>     config:
>       - { id: disk-sda, ptable: gpt, path: /dev/sda, type: disk, wipe: superblock }
>       - { device: disk-sda, grub_device: true, flag: boot, id: sda-efi, number: 1, size: 512MB, type: partition, wipe: superblock }
>       - { device: disk-sda, id: sda-boot, number: 2, size: 1GB, type: partition, wipe: superblock }
>       - { device: disk-sda, id: sda-lvm, number: 3, size: -1, type: partition, wipe: superblock }
>       - { type: dm_crypt, volume: sda-lvm, keyfile: /boot/keyfile, recovery_keyfile: /tmp/luks-recovery-key-3xmf7tb5, recovery_live_location: /root/recovery-key.txt, recovery_backup_location: var/log/installer/recovery-key.txt, path: /dev/mapper/dm_crypt-0, id: dm_crypt-0 }
>       - { type: lvm_volgroup, name: vg00, devices: [dm_crypt-0], id: vg00 }
>       - { type: lvm_partition, volgroup: vg00, id: lvroot, name: lvroot, size: 50G }
>       - { type: lvm_partition, volgroup: vg00, id: lvswap, name: lvswap, size: 10G }
>       - { type: lvm_partition, volgroup: vg00, id: lvhome, name: lvhome, size: 5G }
>       - { type: lvm_partition, volgroup: vg00, id: lvtmp, name: lvtmp, size: 1G }
>       - { type: lvm_partition, volgroup: vg00, id: lvvar, name: lvvar, size: 20G }
>       - { type: format, fstype: fat32, volume: sda-efi, id: sda-efi-fs }
>       - { type: format, fstype: ext4, volume: sda-boot, id: sda-boot-fs }
>       - { type: format, fstype: ext4, volume: lvroot, id: lv-root-fs }
>       - { type: format, fstype: swap, volume: lvswap, id: lv-swap-fs }
>       - { type: format, fstype: ext4, volume: lvhome, id: lv-home-fs }
>       - { type: format, fstype: ext4, volume: lvtmp, id: lv-tmp-fs }
>       - { type: format, fstype: ext4, volume: lvvar, id: lv-var-fs }
>       - { type: mount, path: /boot/efi, id: m-efi, device: sda-efi-fs }
>       - { type: mount, path: /boot, id: m-boot, device: sda-boot-fs }
>       - { type: mount, path: /, id: m-root, device: lv-root-fs }
>       - { type: mount, path: '', id: m-swap, device: lv-swap-fs }
>       - { type: mount, path: /home, id: m-home, device: lv-home-fs }
>       - { type: mount, path: /tmp, id: m-tmp, device: lv-tmp-fs }
>       - { type: mount, path: /var, id: m-var, device: lv-var-fs }
>   version: 1
>   packages:
>     - bash-completion
>     - cloud-utils
>     - cloud-guest-utils
>     - git
>     - curl
>     - mlocate
>     - resolvconf
>     - htop
>     - net-tools
>     - dnsutils
>     - aptitude
>     - unzip
>     - cryptsetup
>     - lvm2
>   early-commands:
>     - curtin in-target --target=/target -- modprobe pkey
>     - curtin in-target --target=/target -- dd if=/dev/urandom of=/boot/keyfile bs=1024 count=4
>     - curtin in-target --target=/target -- chmod 0400 /boot/keyfile
>     - curtin in-target --target=/target -- dd if=/dev/urandom of=/tmp/luks-recovery-key-3xmf7tb5 bs=1024 count=4
>     - curtin in-target --target=/target -- chmod 0400 /tmp/luks-recovery-key-3xmf7tb5
>     - curtin in-target --target=/target -- cp /tmp/luks-recovery-key-3xmf7tb5 /root/recovery-key.txt
>     - curtin in-target --target=/target -- cp /tmp/luks-recovery-key-3xmf7tb5 /var/log/installer/recovery-key.txt
>   late-commands:
>     - curtin in-target --target=/target -- cryptsetup luksAddKey /dev/sda3 /boot/keyfile
>     - echo '%ubuntu ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/ubuntu
> ```

**Comment by lefeck** [comment]
I'm very sorry, I didn't reply to your message in time, I've written a new storage configuration parameter, you can try it and hopefully it will be successful. as follows:

```yaml
  storage:
    grub:
      reorder_uefi: False
      uefi: true
    swap:
      size: 0
    config:
      - { id: disk-sda, type: disk, ptable: gpt, path: /dev/sda, wipe: superblock }
      - { id: sda-efi, type: partition, device: disk-sda, number: 1, size: 512MB, wipe: superblock, flag: [ boot, esp ] }
      - { id: sda-boot, type: partition, device: disk-sda, number: 2, size: 1GB, wipe: superblock }
      - { id: sda-lvm, type: partition, device: disk-sda, number: 3, size: -1, wipe: superblock }

      - { id: dm_crypt-0, type: dm_crypt, volume: sda-lvm, dm_name: crypt-lvm, key: random }

      - { id: vg00, type: lvm_volgroup, name: vg00, devices: [ dm_crypt-0 ] }

      - { id: lvroot, type: lvm_partition, volgroup: vg00, name: lvroot, size: 20G }
      - { id: lvswap, type: lvm_partition, volgroup: vg00, name: lvswap, size: 10G }
      - { id: lvhome, type: lvm_partition, volgroup: vg00, name: lvhome, size: 5G }
      - { id: lvtmp, type: lvm_partition, volgroup: vg00, name: lvtmp, size: 1G }
      - { id: lvvar, type: lvm_partition, volgroup: vg00, name: lvvar, size: 10G }

      - { id: sda-efi-fs, type: format, volume: sda-efi, fstype: fat32 }
      - { id: sda-boot-fs, type: format, volume: sda-boot, fstype: ext4 }
      - { id: lv-root-fs, type: format, volume: lvroot, fstype: ext4 }
      - { id: lv-swap-fs, type: format, volume: lvswap, fstype: swap }
      - { id: lv-home-fs, type: format, volume: lvhome, fstype: ext4 }
      - { id: lv-tmp-fs, type: format, volume: lvtmp, fstype: ext4 }
      - { id: lv-var-fs, type: format, volume: lvvar, fstype: ext4 }

      - { id: m-efi, type: mount, device: sda-efi-fs, path: /boot/efi }
      - { id: m-boot, type: mount, device: sda-boot-fs, path: /boot }
      - { id: m-root, type: mount, device: lv-root-fs, path: / }
      - { id: m-home, type: mount, device: lv-home-fs, path: /home }
      - { id: m-tmp, type: mount, device: lv-tmp-fs, path: /tmp }
      - { id: m-var, type: mount, device: lv-var-fs, path: /var }

  version: 1
  packages:
    - bash-completion
    - cloud-utils
    - cloud-guest-utils
    - git
    - curl
    - mlocate
    - resolvconf
    - htop
    - net-tools
    - dnsutils
    - aptitude
    - unzip
    - cryptsetup
    - lvm2
  early-commands:
    - dd if=/dev/urandom of=/tmp/luks-recovery-key bs=1024 count=4
    - chmod 0400 /tmp/luks-recovery-key

  late-commands:
    - cp /tmp/luks-recovery-key /target/root/recovery-key.txt
    - cp /tmp/luks-recovery-key /target/var/log/installer/recovery-key.txt
    - curtin in-target --target=/target -- cryptsetup luksAddKey /dev/mapper/crypt-lvm /root/recovery-key.txt
    - echo '%ubuntu ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/ubuntu
```

**Comment by maworsham** [comment]
Thanks for the response. Btw, great code for building ISOs.

I had a do a little reconfiguring for how the storage/disk information is laid out, but I was able to get this working. Not actually happy with the results (since I had to use the long format), but it does work. The only other part I couldn't get working in-line was the actual setting of the auto passphrase part with the initial build, even when using late-commands.

```
#cloud-config
autoinstall:
  version: 1
  mirror:
    url: http://us.archive.ubuntu.com/ubuntu
  refresh-installer:
    update: no
    channel: "stable/ubuntu-$REL"
  updates: security
  identity:
    hostname: encrypted
    username: ubuntu
    password: "$y$j9T$fE4./vnSjjBTiB9Fa6sVw1$yhyJYGX2aBSN7GXHtsBCvskiYH7mX9HrQ6dvTdJtc/1"
  keyboard:
    layout: us
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      ens32:
        addresses:
          - 192.168.1.29/24
        nameservers:
          addresses:
           - 192.168.1.3
           - 192.168.1.1
          search:
           - murpe.local
        routes:
          - to: default
            via: 192.168.1.1
    version: 2
  ssh:
    install-server: true
    allow-pw: true
  storage:
    grub:
      reorder_uefi: false
    swap:
      size: 0
    config:
      - id: disk-system
        type: disk
        path: /dev/sda
        ptable: gpt
        wipe: superblock
        name: system
      - id: part-efi
        type: partition
        device: disk-system
        number: 1
        size: 512MB
        flag: boot
        grub_device: true
        wipe: superblock
      - id: part-boot
        type: partition
        device: disk-system
        number: 2
        size: 1G
        wipe: superblock
      - id: part-crypt
        type: partition
        device: disk-system
        number: 3
        size: -1
        wipe: superblock
      - id: crypt-vg
        type: dm_crypt
        volume: part-crypt
        dm_name: crypt-vg
        key: ubuntu
      - id: vg00
        type: lvm_volgroup
        name: vg00
        devices:
          - crypt-vg
      - id: lvroot
        type: lvm_partition
        volgroup: vg00
        name: lvroot
        size: 30G
      - id: lvswap
        type: lvm_partition
        volgroup: vg00
        name: lvswap
        size: 4G
      - id: lvhome
        type: lvm_partition
        volgroup: vg00
        name: lvhome
        size: 5G
      - id: lvtmp
        type: lvm_partition
        volgroup: vg00
        name: lvtmp
        size: 1G
      - id: lvvar
        type: lvm_partition
        volgroup: vg00
        name: lvvar
        size: 15G
      - id: fs-efi
        type: format
        volume: part-efi
        fstype: fat32
      - id: fs-boot
        type: format
        volume: part-boot
        fstype: ext4
      - id: fs-root
        type: format
        volume: lvroot
        fstype: ext4
      - id: fs-swap
        type: format
        volume: lvswap
        fstype: swap
      - id: fs-home
        type: format
        volume: lvhome
        fstype: ext4
      - id: fs-tmp
        type: format
        volume: lvtmp
        fstype: ext4
      - id: fs-var
        type: format
        volume: lvvar
        fstype: ext4
      - id: mount-efi
        type: mount
        device: fs-efi
        path: /boot/efi
      - id: mount-boot
        type: mount
        device: fs-boot
        path: /boot
      - id: mount-root
        type: mount
        device: fs-root
        path: /
      - id: mount-swap
        type: mount
        device: fs-swap
        path: none
      - id: mount-home
        type: mount
        device: fs-home
        path: /home
      - id: mount-tmp
        type: mount
        device: fs-tmp
        path: /tmp
      - id: mount-var
        type: mount
        device: fs-var
        path: /var
  packages:
    - bash-completion
    - cloud-utils
    - cloud-guest-utils
    - git
    - curl
    - mlocate
    - resolvconf
    - htop
    - net-tools
    - dnsutils
    - aptitude
    - unzip
  late-commands:
    - echo '%ubuntu ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/ubuntu
```

The other issue on making it allow for reboots and fill-in the passphrase, has to be done in a little more unique way since I am using LVM. There's a couple of files that need to be modified for UMASK and the Key File Pattern (where to look for it).

```
How to setup auto-login for encrypted LVM server AFTER deployment

echo -n "ubuntu" | sudo tee /root/keyfile > /dev/null
sudo chmod 600 /root/keyfile
sudo cryptsetup luksAddKey /dev/sda3 /root/keyfile --key-file /root/keyfile
sudo vi /etc/crypttab
sudo cat /etc/crypttab
sudo update-initramfs -u -k all
sudo nano /etc/cryptsetup-initramfs/conf-hook
sudo update-initramfs -u -k all
lsinitramfs /boot/initrd.img-$(uname -r) | grep keyfile
echo "RESUME=/dev/mapper/vg00-lvswap" | sudo tee /etc/initramfs-tools/conf.d/resume
sudo update-initramfs -u -k all
sudo nano /etc/initramfs-tools/initramfs.conf
sudo update-initramfs -u -k all
ls -l /boot/initrd.img-$(uname -r)
lsinitramfs /boot/initrd.img-$(uname -r) | grep keyfile
/root/keyfile
reboot
apt update
apt list --upgradable
apt dist-upgrade
lsinitramfs /boot/initrd.img-$(uname -r) | grep keyfile
cat /etc/cryptsetup-initramfs/conf-hook
cat /etc/fstab
cat /etc/crypttab
cat /etc/initramfs-tools/initramfs.conf
sudo update-initramfs -u -k all
```
